# Generated by Django 3.2 on 2021-11-08 05:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rt_bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('points', models.JSONField()),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 7, 23, 51, 3, 752397)),
        ),
        migrations.AlterField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rt_bus.route'),
        ),
    ]
